const SNAPSHOT_AT = "2026-08-03T00:00:00.000Z";
const INVOICE_ID = "technical-production-fixture-v1";

const breakdown = {
  version: "invoice-tax-snapshot-v2",
  source: "product_catalog_at_checkout",
  generated_at: SNAPSHOT_AT,
  currency: "EUR",
  rounding_method: "gross_tax_rate_total_with_deterministic_line_allocation_v1",
  allocation_methods: {
    regular_shipping: "preallocated_by_checkout_adapter_v2",
    book_shipping: "preallocated_by_checkout_adapter_v2",
    discount: "preallocated_by_checkout_adapter_v2",
  },
  rates: [
    {
      tax_rate: 7,
      products: { gross: 42.91, net: 40.1, tax: 2.81 },
      book_covers: { gross: 0, net: 0, tax: 0 },
      regular_shipping: { gross: 4, net: 3.74, tax: 0.26 },
      book_shipping: { gross: 0, net: 0, tax: 0 },
      discount: { gross: 1.07, net: 1, tax: 0.07 },
      total: { gross: 45.84, net: 42.84, tax: 3 },
    },
    {
      tax_rate: 19,
      products: { gross: 11.73, net: 9.86, tax: 1.87 },
      book_covers: { gross: 0, net: 0, tax: 0 },
      regular_shipping: { gross: 1.95, net: 1.64, tax: 0.31 },
      book_shipping: { gross: 0, net: 0, tax: 0 },
      discount: { gross: 1.19, net: 1, tax: 0.19 },
      total: { gross: 12.49, net: 10.5, tax: 1.99 },
    },
  ],
  totals: {
    subtotal: { gross: 54.64, net: 49.96, tax: 4.68 },
    regular_shipping: { gross: 5.95, net: 5.38, tax: 0.57 },
    book_shipping: { gross: 0, net: 0, tax: 0 },
    book_covers: { gross: 0, net: 0, tax: 0 },
    discount: { gross: 2.26, net: 2, tax: 0.26 },
    total: { gross: 58.33, net: 53.34, tax: 4.99 },
  },
} as const;

const products = [
  { key: "product-7-a", productId: "technical-product-7-a", name: "Technisches Testprodukt 7 A", quantity: 1, unitPrice: 12.95, rate: 7, gross: 12.95, net: 12.1, tax: 0.85, isBook: true },
  { key: "product-7-b", productId: "technical-product-7-b", name: "Technisches Testprodukt 7 B", quantity: 4, unitPrice: 7.49, rate: 7, gross: 29.96, net: 28, tax: 1.96, isBook: true },
  { key: "product-19-a", productId: "technical-product-19-a", name: "Technisches Testprodukt 19 A", quantity: 2, unitPrice: 3.99, rate: 19, gross: 7.98, net: 6.71, tax: 1.27, isBook: false },
  { key: "product-19-b", productId: "technical-product-19-b", name: "Technisches Testprodukt 19 B", quantity: 3, unitPrice: 1.25, rate: 19, gross: 3.75, net: 3.15, tax: 0.6, isBook: false },
] as const;

export function buildLexwareProductionFixtureSnapshotsCore() {
  const invoice = {
    id: INVOICE_ID,
    request_id: "technical-fixture-request-v1",
    invoice_number: null,
    invoice_provider: "lexware",
    invoice_cutover_version: "invoice-cutover-2026-08-01-v1",
    selected_payment_method: "bank_transfer",
    fulfillment_method_snapshot: "shipping",
    billing_name_snapshot: "TECHNISCHER TEST – NICHT VERSENDEN",
    billing_street_snapshot: "Synthetischer Testweg 1",
    billing_postal_code_snapshot: "00000",
    billing_city_snapshot: "Teststadt",
    customer_email_snapshot: null,
    child_name_snapshot: null,
    school_name_snapshot: null,
    class_name_snapshot: null,
    customer_note: null,
    admin_note: "Technisches Fixture; keine reale Rechnung.",
    subtotal_amount: 54.64,
    shipping_amount: 5.95,
    book_shipping_amount: 0,
    book_cover_amount: 0,
    discount_amount: 2.26,
    total_amount: 58.33,
    currency: "EUR",
    tax_snapshot_status: "complete",
    tax_snapshot_source: "product_catalog_at_checkout",
    tax_snapshot_version: "invoice-tax-snapshot-v2",
    tax_snapshot_at: SNAPSHOT_AT,
    tax_breakdown_snapshot: breakdown,
    subtotal_net_amount_snapshot: 49.96,
    subtotal_tax_amount_snapshot: 4.68,
    shipping_net_amount_snapshot: 5.38,
    shipping_tax_amount_snapshot: 0.57,
    book_shipping_net_amount_snapshot: 0,
    book_shipping_tax_amount_snapshot: 0,
    book_cover_net_amount_snapshot: 0,
    book_cover_tax_amount_snapshot: 0,
    discount_net_amount_snapshot: 2,
    discount_tax_amount_snapshot: 0.26,
    total_net_amount_snapshot: 53.34,
    total_tax_amount_snapshot: 4.99,
    created_at: SNAPSHOT_AT,
  };
  const items = products.map((product) => ({
    id: `technical-item:${product.key}`,
    invoice_id: INVOICE_ID,
    product_id: product.productId,
    product_name: product.name,
    product_sku: null,
    quantity: product.quantity,
    unit: "Stück",
    unit_price: product.unitPrice,
    total_price: product.gross,
    tax_rate_snapshot: product.rate,
    product_gross_amount_snapshot: product.gross,
    product_net_amount_snapshot: product.net,
    product_tax_amount_snapshot: product.tax,
    tax_snapshot_source: "product_catalog_at_checkout",
    tax_snapshot_version: "invoice-tax-snapshot-v2",
    tax_snapshot_at: SNAPSHOT_AT,
    book_cover_tax_rate_snapshot: null,
    book_cover_net_amount_snapshot: null,
    book_cover_tax_amount_snapshot: null,
    is_book_snapshot: product.isBook,
    book_isbn13_snapshot: null,
    book_cover_selected: false,
    book_cover_name_snapshot: null,
    book_cover_quantity: 0,
    book_cover_unit_price: 0,
    book_cover_total_price: 0,
    source: "technical_fixture",
    notes: null,
  }));
  return { invoice, items };
}
