import { ArrowLeft, CheckCircle2, Clock3, FileText, Mail, RefreshCw, TriangleAlert } from "lucide-react";
import Link from "next/link";
import { loadLexwareAutomationMonitoring } from "@/app/lib/lexware/lexwareAutomationMonitoringService";

export const dynamic = "force-dynamic";
const toneStyles = { green: "border-[#BFE3CD] bg-[#F0FFF6] text-[#246B45]", yellow: "border-[#F1D1A8] bg-[#FFF8EE] text-[#8A4A1F]", red: "border-[#E8B7B9] bg-[#FFF4F4] text-[#B5282D]" };
function formatDate(value: string | null) { if (!value) return "Noch kein Wert"; return new Intl.DateTimeFormat("de-DE", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Berlin" }).format(new Date(value)); }
function formatAge(value: number | null) { if (value === null) return "Keine offenen Vorgänge"; const minutes = Math.floor(value / 60000); return minutes < 1 ? "unter 1 Minute" : `${minutes} Min.`; }

export default async function LexwareAutomationPage() {
  const monitoring = await loadLexwareAutomationMonitoring();
  const pipelineCards = [{ key: "invoice" as const, label: "Rechnung", icon: FileText }, { key: "pdf" as const, label: "PDF", icon: RefreshCw }, { key: "mail" as const, label: "Mail", icon: Mail }];
  return <main className="min-h-screen bg-[#FBF7F0] text-[#102A43]"><section className="mx-auto flex w-full max-w-6xl flex-col gap-5 px-4 py-6 sm:px-6 lg:px-8">
    <header className="rounded-[32px] border border-[#E8DED2] bg-white p-5 shadow-[0_18px_45px_rgba(16,42,67,0.08)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div>
      <Link href="/admin" className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-[#52616F] hover:text-[#102A43]"><ArrowLeft className="h-4 w-4" /> Admin-Bereich</Link><p className="text-xs font-black uppercase tracking-[0.16em] text-[#B5282D]">Betriebsübersicht</p><h1 className="mt-2 text-3xl font-black tracking-tight">Lexware-Automation</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-[#52616F]">Aggregierter Zustand von Rechnung, Original-PDF, Mail-Vorbereitung und Mailversand.</p>
    </div><div className={`rounded-2xl border px-4 py-3 ${toneStyles[monitoring.tone]}`}><p className="text-xs font-black uppercase tracking-[0.14em]">Gesamtstatus</p><p className="mt-1 flex items-center gap-2 text-lg font-black">{monitoring.tone === "green" ? <CheckCircle2 className="h-5 w-5" /> : <TriangleAlert className="h-5 w-5" />}{monitoring.tone === "green" ? "Betrieb läuft" : monitoring.tone === "yellow" ? "Aufmerksamkeit" : "Eingriff prüfen"}</p></div></div></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Automation", monitoring.automationActive], ["Production Write", monitoring.gates.productionWriteEnabled], ["Automatische Mail", monitoring.gates.automaticMailEnabled], ["Provider Lexware", monitoring.gates.providerAfter === "lexware"]].map(([label, active]) => <div key={String(label)} className="rounded-2xl border border-[#E8DED2] bg-white p-4"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#52616F]">{label}</p><p className={`mt-2 text-lg font-black ${active ? "text-[#246B45]" : "text-[#B5282D]"}`}>{active ? "Aktiv" : "Inaktiv"}</p></div>)}</section>
    <section className="rounded-[28px] border border-[#E8DED2] bg-white p-5"><h2 className="text-lg font-black">Scheduler</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Invoice-Cron", monitoring.crons.invoices], ["PDF-Cron", monitoring.crons.pdfs], ["Mail-Vorbereitung", monitoring.crons.mailOrchestration], ["Mailversand", monitoring.crons.mailProcess]].map(([label, present]) => <div key={String(label)} className="flex items-center justify-between rounded-2xl bg-[#FBF7F0] px-4 py-3 text-sm font-bold"><span>{label}</span><span className={present ? "text-[#246B45]" : "text-[#B5282D]"}>{present ? "vorhanden" : "fehlt"}</span></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-3">{pipelineCards.map(({ key, label, icon: Icon }) => { const pipeline = monitoring.pipelines[key]; return <article key={key} className="rounded-[28px] border border-[#E8DED2] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-2xl bg-[#FBF7F0] p-2.5"><Icon className="h-5 w-5" /></span><h2 className="text-xl font-black">{label}</h2></div><span className={`h-3 w-3 rounded-full ${pipeline.tone === "green" ? "bg-[#2F8F5B]" : pipeline.tone === "yellow" ? "bg-[#D38A24]" : "bg-[#B5282D]"}`} aria-label={`Status ${pipeline.tone}`} /></div>
      <dl className="mt-5 grid grid-cols-2 gap-3 text-sm">{Object.entries(pipeline.counts).map(([status, count]) => <div key={status} className="rounded-xl bg-[#FBF7F0] p-3"><dt className="text-xs font-bold text-[#52616F]">{status.replaceAll("_", " ")}</dt><dd className="mt-1 text-xl font-black">{count}</dd></div>)}</dl>
      {key === "mail" && <div className="mt-3 rounded-xl border border-[#E8DED2] p-3 text-sm"><span className="font-bold text-[#52616F]">Delivery-State: </span>{Object.entries(pipeline.deliveryStates).length ? Object.entries(pipeline.deliveryStates).map(([state, count]) => `${state}: ${count}`).join(" · ") : "keine"}</div>}
      <div className="mt-4 space-y-2 border-t border-[#E8DED2] pt-4 text-sm"><p className="flex justify-between gap-3"><span className="text-[#52616F]">Aktive Locks</span><strong>{pipeline.activeLocks}</strong></p><p className="flex justify-between gap-3"><span className="text-[#52616F]">Stale Locks</span><strong className={pipeline.staleLocks ? "text-[#B5282D]" : ""}>{pipeline.staleLocks}</strong></p><p className="flex justify-between gap-3"><span className="text-[#52616F]">Ältester offener Vorgang</span><strong>{formatAge(pipeline.oldestOpenAgeMs)}</strong></p><p className="flex justify-between gap-3"><span className="text-[#52616F]">Letzter Erfolg</span><strong className="text-right">{formatDate(pipeline.lastSucceededAt)}</strong></p></div>
    </article>; })}</section>
    <footer className="flex items-center gap-2 text-xs font-semibold text-[#52616F]"><Clock3 className="h-4 w-4" /> Stand {formatDate(monitoring.checkedAt)} · Gelb ab 4 Min., Rot ab 9 Min.; abgeleitet aus 2-Minuten-Takt und 5-Minuten-Lease.</footer>
  </section></main>;
}
