import assert from "node:assert/strict";
import fs from "node:fs";
import { buildLexwareAutomationMonitoring, LEXWARE_AUTOMATION_CRONS } from "../app/lib/lexware/lexwareAutomationMonitoringCore";
const now = "2026-08-11T20:00:00.000Z"; const crons = Object.values(LEXWARE_AUTOMATION_CRONS);
const job = (status: string, ageMinutes = 1, extra = {}) => ({ status, createdAt: new Date(Date.parse(now) - ageMinutes * 60_000).toISOString(), updatedAt: now, ...extra });
const fixture = (overrides: Record<string, unknown> = {}) => ({ now, providerAfter: "lexware", productionWriteEnabled: true, automaticMailEnabled: true, configuredCrons: crons.map((cron) => ({ ...cron })), pipelines: { invoice: [], pdf: [], mail: [] }, ...overrides });
assert.equal(buildLexwareAutomationMonitoring(fixture()).tone, "green");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("pending")], pdf: [], mail: [] } })).tone, "green");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("pending", 5)], pdf: [], mail: [] } })).tone, "yellow");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("pending", 10)], pdf: [], mail: [] } })).tone, "red");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("retry")], pdf: [], mail: [] } })).tone, "yellow");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("manual_review")], pdf: [], mail: [] } })).tone, "red");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [], pdf: [], mail: [job("manual_review", 1, { deliveryState: "ambiguous_send" })] } })).tone, "red");
assert.equal(buildLexwareAutomationMonitoring(fixture({ pipelines: { invoice: [job("processing", 1, { lockedAt: "2026-08-11T19:50:00Z", lockExpiresAt: "2026-08-11T19:55:00Z" })], pdf: [], mail: [] } })).pipelines.invoice.staleLocks, 1);
assert.equal(buildLexwareAutomationMonitoring(fixture({ productionWriteEnabled: false })).tone, "red");
assert.equal(buildLexwareAutomationMonitoring(fixture({ configuredCrons: crons.slice(1).map((cron) => ({ ...cron })) })).automationActive, false);
const page = fs.readFileSync("app/admin/lexware/page.tsx", "utf8"); const service = fs.readFileSync("app/lib/lexware/lexwareAutomationMonitoringService.ts", "utf8");
assert.doesNotMatch(service, /recipient|sender|email|name|address|subject|body|payload_snapshot/i); assert.doesNotMatch(page, /recipient|sender|email|address|subject|body|payload/i); assert.doesNotMatch(page, /fetch\(|\.rpc\(|\.insert\(|\.update\(|\.delete\(/); assert.match(service, /trigger_source", "checkout_native_lexware"/); assert.equal(buildLexwareAutomationMonitoring(fixture()).pipelines.mail.oldestOpenAt, null);
console.log("Lexware automation monitoring healthy/age/retry/review/ambiguity/lock/gate/PII/empty-state PASS");
